#!/bin/sh
set -e

# Add the dedicated user if it does not exist
if ! getent passwd gptforuds > /dev/null; then
    adduser --system --group --no-create-home --disabled-login --disabled-password gptforuds
fi

exit 0
