name: Compile native binary file

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          # Use a valid GraalVM version that includes Java 17
          graalvm-version: '22.2.0' # Replace with the version you want to use
          java-version: '17'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Install native-image component
        run: gu install native-image

      - name: Print debug information
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          native-image --version

      - name: Compile native application
        run: ./gradlew nativeCompile
        env:
          GRAALVM_HOME: ${{ steps.setup-graalvm.outputs.graalvm-path }}
          JAVA_HOME: ${{ steps.setup-graalvm.outputs.java-home }}
